<a href="https://colab.research.google.com/github/MinhThinhrine/thuchanhML/blob/main/Lab1_21130549_Vo_Minh_Thinh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def task1():
  n= int (input("inter n: "))
  L =[]
  for i in range(n):
    L.append(int(input("n:")))
  print(L)
  print ("min: ", min(L))
  print ("max: ",max(L))
  print("sum: ",sum(L))
  L.sort()
  print(L)

  positive =0
  negative =0
  for i in L:
    if i%2:
      positive = positive +1
    else :
      negative = negative + 1
  print("positive: ", positive)
  print("negative: ", negative)

def S(n):
  if n == 0:
    return 1
  else:
    return n*S(n-1)

task1()
s= int (input("inter num s: "))
print("compute S: S= ",S(s))

inter n: 2
n:1
n:2
min:  1
max:  2
sum:  3
positive:  1
negative:  1


6

In [ ]:
class Account:
  def __init__(self, name, email, country, friends, posts):
    self.__name = name
    self.__email = email
    self.__country = country
    self.__friends = friends
    self.__posts = posts

  def addPost(self, post):
    self.__posts.append(post)
  def getName(self):
        return self.__name
  def getCountry(self):
        return self.__country
  def getPosts(self):
        return self.__posts
  def __str__(self):
        return f"Account: {self.__name}, Email: {self.__email}, Country: {self.__country}"

  def getMaxLikePostByFriend(self):
    maxLike =0
    maxPost = None
    for friend in self.__friends:
      for post in friend.getPost():
        if post.getLikes() >maxLike:
          maxLike = post.getLikes()
          maxPost = post

class Post:
  def __init__(self, content, subject, likes):
    self.__content = content
    self.__subject = subject
    self.__likes = likes

class AccountManager:
  def __init__(self, account):
    self.__account = account
  def groupAccountsByPostLike(self):
    result = {}
    for account in self.__account:
      if len(account.getPosts()) < 10:
        result[account] = False
      else:
        result[account] = True

    return result

  def filterAccounts(self, country):
    filtered_accounts = [account for account in self.__account if account.getCountry() == country]
    sorted_accounts = sorted(filtered_accounts, key=lambda account: (-len(account.getPosts()), account.getName()))
    return sorted_accounts

account1 = Account("John", "john@example.com", "USA", [], [])
account2 = Account("Alice", "alice@example.com", "UK", [], [])

post1 = Post("Hello world!", "Introduction", 10)
post2 = Post("I love coding!", "Programming", 15)

account1.addPost(post1)
account2.addPost(post2)

account_manager = AccountManager([account1, account2])

grouped_accounts = account_manager.groupAccountsByPostLike()
print("Grouped Accounts:")
for account, has_many_posts in grouped_accounts.items():
    print(f"Account: {account}, Has Many Posts: {has_many_posts}")

filtered_accounts = account_manager.filterAccounts("USA")
print("\nFiltered Accounts:")
for account in filtered_accounts:
    print(account)

Grouped Accounts:
Account: Account: John, Email: john@example.com, Country: USA, Has Many Posts: False
Account: Account: Alice, Email: alice@example.com, Country: UK, Has Many Posts: False

Filtered Accounts:
Account: John, Email: john@example.com, Country: USA


In [ ]:
import numpy as np
def numPy():
  arr = np.arange(10, 26)
  print("Original array:", arr)
  reversed_arr = np.flip(arr)
  print("Reversed array:", reversed_arr)

def repeat():
  L =[1, 2, 3, 4]
  print("Original array: ", L)

  r = L.copy()
  for i in L:
        r.append(i)
  print("Repeating 2 times: ", r)
  copy = r.copy()
  for i in L:
    copy.append(i)
  print("Repeating 3 times: ", copy)
def replace():
  arr = np.array([[0.42, 0.48, 0.32],
        [ 0.74, 0.58, 0.38],
        [ 0.51, 0.34, 0.15]])
  arr[arr > 0.5] = 0.5
  print(arr)

numPy()
repeat()
replace()

Original array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
Reversed array: [25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
Original array:  [1, 2, 3, 4]
Repeating 2 times:  [1, 2, 3, 4, 1, 2, 3, 4]
Repeating 3 times:  [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
